### ISSUE TITLE
New VEBA Doc Updates

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#536]
**Is your feature request related to a problem? Please describe.**

- [x] Update Docs to reflect new Webhook Event Provider including OVF params
- [x] Update Docs to reflect new Horizon Event Provider including OVF params
- [x] Update Docs diagram to reflect additional Event Providers (depends on #535)
- [x] Update Docs to reflect deprecated Event Processors (see #500 for more details)
- [x] Update Docs for Function Development and focus on Knative (depends on #491)
- [x] Update Docs for Function Troubleshooting (depends on #610) 
- [x] Update Docs for Getting Started  (depends on #611) 
- [x] Update Docs for VEBA Timeline (depends on #620)
- [x] Update Docs for VEBA Website (depends on #618)
