### ISSUE TITLE
EPIC: Migrate OF examples to Knative backend

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#677]
Functions (tbd, excluding those already available in Kn):

- [x] #684
- [ ] VM reconfig via Tag (Go)
- [ ] Pagerduty trigger (Go)
- [ ] Tagging (Go)
- [ ] Plugin Auto-Refresh (Java)
- [ ] Veeam VM Backup (Java)
- [ ] #877 
- [x] #856 
- [x] #867 
- [ ] HW Change Slack (PCLI)
- [ ] NSX Tag Sync vRO (PS)
- [ ] vRO (PS)
- [ ] ESX MTU Fixer (Python)
- [ ] Invoke REST API (Python)
- [ ] Pre-Filter (Python)
- [ ] Tagging (Python)
- [ ] Trigger Pagerduty Incident (Python)
