### ISSUE TITLE
EPIC: Update documentation for VI Admins

### ISSUE THREAD

**Issue by AndyTauber** [vmware-samples/vcenter-event-broker-appliance#732]
- [ ] Describe knative in Introduction
- [ ] Expand Knative Prerequisites in Deploy Functions
- [ ] Add example into the "Knative Function Deployment using vSphere UI" section
- [x] #736

**Comment by embano1** [comment]
@AndyTauber please let me know which issues (tasks) are already resolved and whether you plan to contribute the rest in a later milestone or if we should close this EPIC.

**Comment by AndyTauber** [comment]
We should close this EPIC, the items other than the tutorial have been addressed by other updates to the documentation over the last months.
